# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13ffae8508e6302216977dfe8cc9f9f7e3955d2e7df53273eba7ad0425aec7c4b68b6f401bae652afcb1ce08634994bab48f1ac1c9c7aec2cad6155833fba525

test:
  secret_key_base: 0d7ddb63e9c228d0610e3907e6c10a265b2d62fc81afe1c0cf733200366f01efaa409e87f484c651ab70c0480d1b04be4e293cd9cade025746fb81355f8c591e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
